apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: db
spec:
  ports:
    - port: 6379
  selector:
    app: db
    name: redis
---
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: db
        name: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        livenessProbe:
          tcpSocket:
            port: 6379
        ports:
        - containerPort: 6379
          name: redis
